### ISSUE TITLE
欠陥

### ISSUE THREAD

**Issue by Akatsuki1910** [nitnc-17s/maze#1]
プログラム上は動くが速度が安定しない

**Comment by LaFr4nc3** [comment]
Issueのタイトルは具体的なものにしてください

**Comment by Akatsuki1910** [comment]
ごめんなさい叩かないでくださいこれ以上私がだすものはありません金を巻き上げないでください

**Comment by Nishinoyama** [comment]
なにわろてんねん[krunker.io](草)

**Comment by LaFr4nc3** [comment]
Issueにスパムを書き込まないでください

**Comment by jellyfish26** [comment]
荒らしがいるのでcloseします．お疲れ様でした．
